name: Process Python Module
on:
  push:
    branches:
      - '**'
    paths:
      - src/**
      - .github/workflows/**
    tags:
      - v*
  pull_request:
    branches:
      - main

jobs:
  build:

    name: Build module
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.8
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id:   gitversion
        uses: gittools/actions/gitversion/execute@v0.9.8
        with:
          useConfigFile: true
          configFilePath: GitVersion.yml

      - name: Set up Python 3.9.1
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.1

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install pylint requests

      - name: Run Pylint
        run: |
          pylint ./src

      - name: Zip code
        run: |
          zip -r release.zip src -x "src/examples.py"

      - name: Upload Release artifact
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: ${{ github.workspace }}/release.zip

  prod_release:

    name: Prod Release module
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    needs: build

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        with:
          configuration: "config/changelogConfig.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download artifact
        uses: actions/download-artifact@v2

      - name: Display structure of downloaded files
        run: ls -R

      # - name: Create Release
      #   id: create_release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     name: "pyBrickset"
      #     artifacts: ".\\release\\*.zip"
      #     body: ${{steps.github_release.outputs.changelog}}
      #     token: ${{ secrets.GITHUB_TOKEN }}
